print('Hello World!')
print('Waht is your name?')
name=input()
print('It is good to ,eet you,'+ name)
print('The length of your name is:')
print(len(name))
print('What is your age?')
age=input()
print('You will be ' + str(int(age)+1) +'in a year')
